name: hyper_ars
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - tensorflow==2.12.0
  - scipy
  - matplotlib
  - ipykernel
  - ca-certificates
  - certifi
  - openssl
  - scikit-learn
  - keras==2.12.0
  - numpy==1.23.5
# prefix: /Users/rabinatwayana/Rabina/anaconda3/envs/hyper_ars
